language: shell

dist: xenial

os: linux

before_install:
  - sudo apt-get update

# delete in progress images
after_failure:
  - cd releases
  - ../build/cleanup.sh

## 3 archs  matrix
os: linux
arch:
  - amd64
  - ppc64le
  - s390x

## build all releases and push in progress images on master
script:
- uname -a
- cat /etc/issue
- cd build
- ./buildAll.sh --release $RELEASE

## build manifest list for each release and delete in progress images
jobs:
  include:
    - stage: build-fat-manifest
      if: branch=master AND type!=pull_request
      script:
      - uname -a
      - cat /etc/issue
      - cd releases
      - wget https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64 -O manifest-tool
      - chmod +x manifest-tool
      - ../build/buildManifest.sh
